displayName: Basic Auth powered by Kuzzle
type: middleware
import: github.com/alexandrebouthinon/traefik-plugin-kuzzle-basic-auth
summary: Traefik Basic Auth Plugin powered by Kuzzle
testData:
  basic-auth:
    user: admin
    password: aSimplePassword
  kuzzle:
    host: localhost
    port: 7512
    ssl: false