displayName: Basic Auth powered by Kuzzle
type: middleware
import: github.com/alexandrebouthinon/traefik-kuzzle-auth
summary: Traefik Basic Auth middleware powered by Kuzzle
iconPath: assets/icon.png
testData:
  customRealm: "Use a valid Kuzzle user to authenticate"
  kuzzle:
    url: "http://localhost:7512"
    routes:
      ping: /_publicApi
      login: /_login/local
      getCurrentUser: /_me # With Kuzzle v1 you must use '/users/_me'
    allowedUsers:
      - admin
      - developer